export const GET_SONGS_REQUESTED = 'GET_SONGS_REQUESTED';
export const GET_SONGS_SUCCEDED = 'GET_SONGS_SUCCEDED';
export const GET_SONGS_FAILED = 'GET_SONGS_FAILED';
export const ADD_FAVOURITE_SONG_REQUESTED = 'ADD_FAVOURITE_SONG_REQUESTED';
export const REMOVE_FAVOURITE_SONG_REQUESTED = 'REMOVE_FAVOURITE_SONG_REQUESTED';
